server:
  port: 8092
 
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:msdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2  
  application:
   name: Admin-Service  

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value} 

  client:    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka   
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health: 
      show-details: "ALWAYS"
 
pivotal:
  employeeservice:
    name: Employee-Service
  loginservice:
    name: Login-Service
  adminservice:
    name: Admin-Service
